env: "healthy"
data: "AB06"
visualize: False
log_wandb: False
train_mode: True
n_steps: 256
ppo_epochs: 2
ppo_batchsize: 32
ppo_kl_range: 0.05
slope_rollback: 5.0
slope_likelihood: 1
initial_logstd: -1.34
val_clip_range: 1.0
entropy_coef: 0.0
vf_loss_coef: 1.0
aux_update: 32
aux_epochs: 6
aux_batchsize: 64
beta_clone: 1.0
gamma: 0.99
lambd: 0.95
learning_rate: 2.5e-4