env: "healthy"
data: "AB06"
visualize: False
log_wandb: False
train_mode: True
n_steps: 256
n_ppo_epochs: 2
ppo_batch_size: 32
ppo_delta: 0.05
ppo_alpha: 5.0
initial_logstd: -1.34
value_clip: 1.0
entropy_coef: 0.0
vf_loss_coef: 1.0
n_aux_update: 32
n_aux_epochs: 6
aux_batch_size: 64
beta_clone: 1.0
gamma: 0.99
lambd: 0.95
learning_rate: 2.5e-4